name: service
description: |
 Services

 Just a list of services that exist. Modules do register their services here.
 Use system._setup_register_service(<module>, <service>) to insert into this
 table.

primary_key:
 - service

templates:
 - commons.options

columns:
 -
  name: service
  type: commons.t_key
  description: Service name
 -
  name: module
  type: commons.t_key
  description: Module name, just to keep track who uses this name
