name: web
description: |
 Websites

 This module sends the following signals:
  - web/alias
  - web/site

dependencies:
 - server_access

priv_all_all:
 - system
priv_usage:
 - userlogin
 - backend

exec_post_install_and_upgrade: |
 SELECT system._setup_register_service('web', 'web');
 SELECT system._setup_register_subservice('web', 'site');
 SELECT system._setup_register_subservice('web', 'alias');
 SELECT system._setup_register_subservice('web', 'dns_activatable');
 SELECT system._setup_register_subservice('web', 'http_redirect');

