name: service
description: Name server entries based on system.service (i.e. system.service_dns)

templates:
 - system.reference_service_entity
 - backend.status

primary_key:
 - domain
 - service

unique:
 -
  name: unique
  columns:
   - domain
   - service
   - service_entity_name

columns:
 -
  name: registered
  type: dns.t_domain
  description: Registered domain of which domain is a sub domain
  references: dns.registered.domain
 -
  name: domain
  type: dns.t_domain
  description: domain for which the entries should be created

checks:
 -
  name: proper_subdomain
  description: Ensures that domain is a subdomain of registered
  check: registered = right(domain, char_length(p_registered))

