name: service
description: Name server entries based on system.service (i.e. system.service_dns)

templates:
 - system.reference_service_entity
 - backend.status

primary_key:
 - domain
 - service

unique:
 -
  name: unique
  columns:
   - domain
   - service
   - service_entity_name

columns:
 -
  name: registered
  type: dns.t_hostname
  description: Registered domain of which domain is a sub domain
  references: dns.registered.domain
 -
  name: domain
  type: dns.t_hostname
  description: domain for which the entries should be created

checks:
 -
  name: is_subdomainof_registered
  description: Ensures that domain is a subdomain of registered
  check: dns._is_subdomain_of(domain, registered)
