name: backend
description: |
 Carnivora Backend

 The backend module provides everything required for the backend API.
 The backend API delivers content required for building configs etc.
 to clients, called machines.

dependencies:
 - email
 - system

priv_all_all:
 - system

roles:
 -
  name: backend
  description: vms

domains:
 -
  name: t_status
  description: Backend status
  type: character varying(20)

function_templates:
 -
  template: backend
  description: |
      Tries to identify if connected role has the right to perform
      backend tasks for some machine. If this is the case, it
      identifies the machine. Otherwise it rises an exception.
  parameters:
    -
     name: p_include_inactive
     type: boolean
     default: "false"
  variables:
   -
    name: v_machine
    type: dns.t_hostname
  security_definer: true
  owner: system
  priv_execute:
   - backend

  body_prelude: |
   v_machine := (SELECT "machine" FROM "backend"._get_login());

 -
  template: backend_login
  description: |
   Same as ``backend``, just without parameters etc.
  variables:
   -
    name: v_machine
    type: dns.t_hostname
  priv_execute:
   - backend
  body_prelude: |
   v_machine := (SELECT "machine" FROM "backend"._get_login());

table_templates:
 -
  template: status
  description: Backend
  columns:
   -
      name: backend_status
      description: |
          Status of database entry in backend. NULL: nothing pending,
          'ins': entry not present on backend client, 'upd': update
          pending on backend client, 'del': deletion peding on
          backend client.
      type: backend.t_status
      default: "'ins'"
      null: true
