#!/bin/bash -e

psql -c "
-- http://stackoverflow.com/questions/5108876/kill-a-postgresql-session-connection
SELECT 
    pg_terminate_backend(pid) 
FROM 
    pg_stat_activity 
WHERE 
    -- don't kill my own connection!
    pid <> pg_backend_pid()
    -- don't kill the connections to other databases
    AND datname = 'test1';
" postgres postgres

../hamsql/Main -p -c"postgres://postgres@"> sql.sql
../hamsql/Main -d > doc/doc.html
../hamsql/Main -g > doc/doc-graph.dot
dot -Tpdf -o doc/doc-graph.pdf doc/doc-graph.dot
cp doc/doc.html ../carnivora-doc/index.html
cp doc/s.css ../carnivora-doc/

../hamsql/Main -e -c"postgres://postgres@/test1"

export PAGER=cat
psql -P null=/NULL/ --set ON_ERROR_STOP=1 -f "test/prepare.sql" test1 postgres
psql -P null=/NULL/ --set ON_ERROR_STOP=1 -f "test/frontend.sql" test1 carnivora_edentata
psql -P null=/NULL/ --set ON_ERROR_STOP=1 -f "test/backend.sql" test1 carnivora_mailserver

