#!/bin/bash -e

psql -c "
-- http://stackoverflow.com/questions/5108876/kill-a-postgresql-session-connection
SELECT 
    pg_terminate_backend(pid) 
FROM 
    pg_stat_activity 
WHERE 
    -- don't kill my own connection!
    pid <> pg_backend_pid()
    -- don't kill the connections to other databases
    AND datname = 'test1';
" postgres postgres
psql -c "DROP DATABASE test1;" postgres postgres
psql -c "CREATE DATABASE test1;" postgres postgres

../hamsql/Main -p > sql.sql
../hamsql/Main -d > doc/doc.html
../hamsql/Main -g > doc/doc-graph.dot
dot -Tpdf -o doc/doc-graph.pdf doc/doc-graph.dot

cp doc/doc.html ../carnivora-doc/index.html
cp doc/s.css ../carnivora-doc/

../hamsql/Main -e -c"postgres://postgres:a@localhost/test1"

export PAGER=cat
psql -P null=/NULL/ -f "test/test.sql" test1 postgres

