name: domain_reseller
description: |
 Features for Domains Registered via a Reseller

 Stores additional details for dns.registered domains. Also supports storing
 contact informations (handles).

 This module sends the following signals:
  - domain_reseller/handle
  - domain_registered/managed
  - domain_registered/unmanaged

dependencies:
 - dns

priv_all_all:
 - system
priv_usage:
 - userlogin
 - backend

exec_post_install_and_upgrade: |
 SELECT system._setup_register_service('domain_reseller', 'domain_reseller');
 SELECT system._setup_register_subservice('domain_reseller', 'handle');
 SELECT system._setup_register_subservice('domain_reseller', 'domain');
