name: service
description: |
 Just a list of services that exist. Modules do register their names
 here.

 Use system.setup_register_service(...) to insert into this table.

primary_key:
 - service

columns:
 -
  name: service
  type: commons.t_key
  description: Service name
 -
  name: module
  type: commons.t_key
  description: Module name, just to keep track who uses this name
