name: service
description: |
 Names under which services are made available. For example (mail.example.org, email)
 could be a mail-server system referred to as mail.example.org by carnivora.
 Such a system can consist of multiple physical or virtual machines. The corresponding
 machines are listed in system.service_machine. A core feature of services is the
 definition of 'templates' for dns records that have to be present for every domain 
 that uses this service. Such 'templates' have to be defined in system.service_dns.
 They can be assigned to specific domains in dns.service.

 The service_name might be exposed to the client as address he has connect to. For
 example as SMTP or SSH server etc. The exact interpretation of the service_name
 depends on the module and the frontend.

primary_key:
 - service_name
 - service

columns:
 -
  name: service_name
  type: dns.domain_name
  description: Host name
 -
  name: service
  type: varchar(50)
  description: email, ssh, ...
  references: system.service_index.service

