name: service
description: Names under which services are made available. Bound to machines.

primary_key:
 - service_name
 - service

columns:
 -
  tag: column
  name: service_name
  type: dns.domain_name
  description: Host name
 -
  tag: column
  name: service
  type: varchar
  description: email, ssh, ...

