name: site
description: |
 Website

templates:
 - dns.reference_service
 - system.reference_subservice_entity
 - backend.status
 - commons.options

primary_key:
 - domain
 - port

columns:
 -
  name: port
  type: commons.t_port
  description: Port
 -
  name: storage_user
  type: server_access.t_user
  description: Server account under which the htdocs reside
 -
  name: storage_service
  type: commons.t_key
  description: TODO
 -
  name: storage_service_entity_name
  type: dns.t_domain
  description: TODO
 -
  name: ssl
  type: uuid
  null: true
  description: If null, HTTPS is deactivated

checks:
 -
  name: valid redirection
  description: Ensure redirect URL exists for redirection
  check: subservice <> 'http_redirect' OR (option->>'redirect_url')::varchar IS NOT NULL

foreign_keys:
 -
  name: https
  columns:
   - ssl
   - service
   - service_entity_name
  ref_table: ssl.demand
  ref_columns:
   - id
   - service
   - service_entity_name

 -
  name: server_access
  columns:
   - storage_user
   - storage_service
   - storage_service_entity_name
  ref_table: server_access.user
  ref_columns:
   - user
   - service
   - service_entity_name

unique:
 -
  name: unique
  columns:
   - domain
   - service_entity_name
   - port
