name: site
description: |
 Website

templates:
 - dns.reference_service
 - system.reference_subservice_entity
 - backend.status
 - commons.options
 - user.ownable

primary_key:
 - domain
 - port

columns:
 -
  name: port
  type: commons.t_port
  description: Port
 -
  name: user
  type: server_access.t_user
  description: Server account under which the htdocs reside
 -
  name: https
  type: bool
  description: HTTPS

checks:
 -
  name: valid redirection
  description: Ensure redirect URL exists for redirection
  check: subservice <> 'http_redirect' OR (option->>'redirect_url')::varchar IS NOT NULL

foreign_keys:
 -
  name: server_access
  columns:
   - user
   - service_entity_name
   - owner
  ref_table: server_access.user
  ref_columns:
   - user
   - service_entity_name
   - owner
  on_update: cascade

unique:
 -
  name: unique
  columns:
   - domain
   - service_entity_name
   - port
