name: server_access
description: |
 Server Access

 Explicit passwd entries for shell acounts and sftp.

 This module sends the following signals:
  - server_access/sftp
  - server_access/ssh

dependencies: 
 - system
 - user

priv_all_all:
 - system
priv_usage:
 - userlogin
 - backend

exec_post_install_and_upgrade: |
 SELECT system._setup_register_service('server_access', 'server_access');
 SELECT system._setup_register_subservice('server_access', 'ssh');
 SELECT system._setup_register_subservice('server_access', 'sftp');

domains:
 -
  name: t_user
  type: varchar(30)
  description: |
   Unix user. This type only allows a subset of those names allowed by POSIX.

  checks:
   -
    name: valid_characters
    description: Only allow lower-case characters.
    check: VALUE ~ '^[a-z0-9_-]+$'
   -
    name: no_repeated_hyphens
    description: |
     Reserve double hyphens as a seperator for system generated users.
    check: NOT (VALUE LIKE '%--%')
   -
    name: no_starting_hyphen
    description: |
     No hyphens at the beginning:
     http://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap03.html#tag_03_431
    check: left(VALUE, 1) <> '-'
