name: dns
description: |
 DNS and Registered Domains
 
 The entity name for **domain_registered** services are considered the
 *nameservers* used for this domain. In case of the *unmanaged* subservice, a
 a fake name or the responsible nameserver that is not managed by the system
 can be given.
 
 To allow service activation, the service needs a ``dns_activatable``
 subservice entity.
 
 .. todo::
  Document *managed_custom*. Unclear if this is even properly supported or checked.

dependencies:
 - commons

priv_all_all:
 - system
priv_usage:
 - userlogin
 - backend


exec_post_install_and_upgrade: |
 SELECT system._setup_register_service('dns', 'domain_registered');
 SELECT system._setup_register_service('dns', 'dns');
 SELECT system._setup_register_subservice('domain_registered', 'managed');
 SELECT system._setup_register_subservice('domain_registered', 'managed_custom');
 SELECT system._setup_register_subservice('domain_registered', 'unmanaged');
 SELECT system._setup_register_subservice('dns', 'managed');

domains:

 -
  name: t_domain
  description: Fully qualified domain name (without trailing dot)
  type: varchar
  checks:
   -
    name: domain valid regex
    description: check domain validity
    check: |
     VALUE ~ '^[a-z\d][a-z\d-]{0,62}(\.[a-z\d][a-z\d-]{0,62})+$' AND
     octet_length(VALUE) <= 253
 -
  name: t_domain_rdata
  description: |
    Fully qualified or relative domain name. Trailing dot marks a FQDN.
  type: varchar
  checks:
   -
    name: invalid rdata domain
    description: check
    check: |
     (VALUE ~ '^([a-z\d][a-z\d-]{0,62}\.)+$' OR
      VALUE ~ '^([a-z\d][a-z\d-]{0,62}\.)*[a-z\d][a-z\d-]{1,63}$') AND
     octet_length(VALUE) <= 253

 -
  name: t_type
  description: Resource record type
  type: varchar(253)
  checks:
   -
    name: Invalid or unsupported resource type
    description: Resource type (A, AAAA, CNAME, MX, SRV, TXT, ...)
    check: |
     VALUE IN (
      'A',
      'AAAA',
      'CNAME',
      'MX',
      'NS',
      'SRV',
      'SSHFP',
      'TXT'
     )

 -
  name: t_rdata
  description: Resource record data (Rdata)
  type: jsonb

 -
  name: t_ttl
  description: time to live
  type: integer
  checks:
   -
    name: ttl range
    description: Ensure that TTL is at least one minute and put maximum to 48h
    check: VALUE >= 60 AND VALUE <= 172800

table_templates:
 -
  template: resource_record
  description: Resource record
  columns:
    -
     name: type
     type: dns.t_type
     description: Type (A, AAAA, CNAME, MX, SRV, TXT, ...)
    -
     name: rdata
     type: dns.t_rdata
     description: fancy rdata storage
    -
     name: ttl
     description: Time to live, NULL indicates default value
     type: dns.t_ttl
     null: true
  checks:
   -
    name: invalid_rdata_A
    description: A
    check: |
        type<>'A' OR
        rdata ? 'address' AND
        (rdata->>'address')::cidr IS NOT NULL
   -
    name: invalid_rdata_AAAA
    description: AAAA
    check: |
        type<>'AAAA' OR
        rdata ? 'address' AND
        (rdata->>'address')::cidr IS NOT NULL
   -
    name: invalid_rdata_CNAME
    description: CNAME
    check: |
        type<>'CNAME' OR
        rdata ? 'cname' AND
        (rdata->>'cname')::dns.t_domain_rdata IS NOT NULL
   -
    name: invalid_rdata_MX
    description: MX
    check: |
        type<>'MX' OR
        rdata ? 'priority' AND
        rdata ? 'exchange' AND
        (rdata->>'priority')::int >= 0 AND
        (rdata->>'exchange')::dns.t_domain_rdata IS NOT NULL

   -
    name: NS
    description: NS
    check: |
        type<>'NS' OR
        rdata ? 'nsdname' AND
        (rdata->>'nsdname')::dns.t_domain_rdata IS NOT NULL
   -
    name: invalid_rdata_SRV
    description: SRV
    check: |
        type<>'SRV' OR
        rdata ? 'service' AND
        rdata ? 'proto' AND
        rdata ? 'priority' AND
        rdata ? 'weight' AND
        rdata ? 'port' AND
        rdata ? 'target' AND
        (rdata->>'service')::commons.t_key IS NOT NULL AND
        (rdata->>'proto')::commons.t_key IS NOT NULL AND
        -- Limit integer range
        (rdata->>'priority')::commons.t_port IS NOT NULL AND
        (rdata->>'weight')::commons.t_port IS NOT NULL AND
        (rdata->>'port')::commons.t_port IS NOT NULL AND
        -- Could be relative or absolute
        (rdata->>'target')::varchar IS NOT NULL
   -
    name: invalid_rdata_SSHFP
    description: SSHFP
    check: |
        type<>'SSHFP' OR
        rdata ? 'algorithm' AND
        rdata ? 'fptype' AND
        rdata ? 'fingerprint' AND
        (rdata->>'algorithm')::int >= 0 AND
        (rdata->>'fptype')::int >= 0 AND
        octet_length((rdata->>'fingerprint')::commons.t_hexvarchar) <= 255
   -
    name: invalid_rdata_TXT
    description: TXT
    check: |
        type<>'TXT' OR
        rdata ? 'txtdata' AND
        commons._jsonb_to_array(rdata->'txtdata') IS NOT NULL AND
        -- minimum number of strings is 1
        cardinality(commons._jsonb_to_array(rdata->'txtdata')) >= 1 AND
        -- check if there are strings with more then 255 bytes
        dns._rdata_txtdata_valid(commons._jsonb_to_array(rdata->'txtdata'))

 -
  template: reference_service
  description: Reference service
  columns:
   -
    name: domain
    type: dns.t_domain
    description: Domain name
   -
    name: service
    type: commons.t_key
    description: Service
   -
    name: service_entity_name
    type: dns.t_domain
    description: ent. name

  foreign_keys:
   -
    name: reference dns (service)
    columns:
     - domain
     - service
     - service_entity_name
    ref_table: dns.service
    ref_columns:
     - domain
     - service
     - service_entity_name
