name: user
description: |
 Carnivora Users: Users own things objects in the DB,
 and they can login into frontends (edentata)

dependencies:
 - commons

priv_all_all:
 - system
priv_usage:
 - userlogin

roles:
 -
  name: userlogin
  description: Do user actions via this group
  login: false
 -
  name: system
  description: Highly priviledged user
  login: false

function_templates:
 -
  template: userlogin
  description: complicated...
  security_definer: true
  owner: system
  priv_execute:
   - userlogin

  variables:
   -
    name: v_owner
    type: user.t_user
   -
    name: v_login
    type: user.t_user

  body_prelude: |
   -- begin userlogin prelude
   v_login := (SELECT t.owner FROM "user"._get_login() AS t);
   v_owner := (SELECT t.act_as FROM "user"._get_login() AS t);
   -- end userlogin prelude

table_templates:
 -
  template: ownable
  description: For tables in which rows can be owned by users.

  columns:
   -
    name: owner
    type: user.t_user
    description: Owner
    references: user.user.owner
    on_ref_update: CASCADE

domains:
 -
  name: t_user
  type: commons.t_key
  description: Username
