name: ssl
description: |
 SSL Certificates

dependencies:
 - system

priv_all_all:
 - system
priv_usage:
 - userlogin
 - backend

exec_post_install_and_upgrade: |
 SELECT system._setup_register_service('ssl', 'ssl');
 SELECT system._setup_register_subservice('ssl', 'acme');
 SELECT system._setup_register_service('ssl', 'manual');

function_templates:
 - template: openssl
   description: OpenSSL
   body_prelude: |
    from OpenSSL import crypto
    import datetime
    from cryptography.hazmat.primitives.serialization import Encoding
    from cryptography.hazmat.primitives.serialization import PublicFormat

    def selExtension(shortName, extensions):
        for x in extensions:
            if x.get_short_name() == shortName:
                return x
        else:
            None
                
    def getAltDnsNames(extensions):
        altExtension = selExtension(b'subjectAltName', extensions)
        if altExtension:
            for x in map(str.strip, str(altExtension).split(',')):
                split = x.split(':')
                if len(split) == 2 and split[0] == 'DNS':
                    yield split[1]

    def getPublicBytes(crt):
        return crt.get_pubkey().to_cryptography_key() \
                .public_bytes(Encoding.DER, PublicFormat.SubjectPublicKeyInfo)
    
    def asn1Time(asn1time):
        return datetime.datetime.strptime(asn1time.decode('ascii'), '%Y%m%d%H%M%SZ')

