name: system
description: |
 Carnivora System

 Manages services, service entities and contingents.
dependencies:
 - dns

priv_all_all:
 - system
priv_usage:
 - userlogin

table_templates:
 -
  template: reference_service_entity
  description: Reference to system.service_entity
  columns:
   -
    name: service_entity_name
    type: dns.t_domain
    description: Service entity name
   -
    name: service
    type: commons.t_key
    description: Service (e.g. email, jabber)

  foreign_keys:
   -
    name: Reference service entity
    columns:
     - service_entity_name
     - service
    ref_table: system.service_entity
    ref_columns:
     - service_entity_name
     - service

 -
  template: reference_subservice_entity
  description: Reference to system.subservice_entity
  columns:
   -
    name: subservice
    type: commons.t_key
    description: Subservice (e.g. account, alias)

  foreign_keys:
   -
    name: Reference subservice entity
    columns:
     - service_entity_name
     - service
     - subservice
    ref_table: system.subservice_entity
    ref_columns:
     - service_entity_name
     - service
     - subservice
