name: commons
description: |
 Carnivora Commons

 Usefull templates, functions and domains.

dependencies:
 - backend
 - dns
 - system
 - user

priv_all_all:
 - system

table_templates:
 -
  template: options
  description: Adds JSON options
  columns:
   -
    name: option
    description: Free options in JSON format
    type: jsonb
    default: "'{}'"
 -
  template: uid
  description: Adds uid column
  columns:
   -
    name: uid
    type: integer
    description: Unix user identifier
    default: nextval('commons.uid')
    checks:
     -
      name: range
      description: Range
      check: uid > 100000 AND uid < 200000

domains:
 -
  name: t_port
  type: integer
  description: Port
  checks:
   -
    name: invalid_port
    description: Only allow port values
    check: VALUE >= 0 AND VALUE <= 65535
 -
  name: t_password
  type: varchar(250)
  description: |
      unix hash thingy

      .. todo:: propper checking of format
  checks:
   -
    name: crypt(3) password format
    description: Only allows SHA512 strings.
    check: VALUE ~ '^\$6\$[.\/a-zA-Z0-9]{8,16}\$[.\/a-zA-Z0-9]{86}$'

 -
  name: t_password_plaintext
  type: varchar(255)
  description: Password in plaintext
  checks:
   -
    name: minimum password length 8
    description: Ensures that passwords at least have 8 chars
    check: character_length(VALUE) >= 8

 -
  name: t_key
  type: varchar(50)
  description: Key
 -
  name: t_hexvarchar
  type: varchar
  description: Varchar only with HEX values
  checks:
   -
    name: invalid characters
    description: Only allows numbers and chars a-f for hex representation
    check: VALUE ~ '^[0-9a-f]*$'

function_templates:
 -
  template: public_util
  description: Allows public access to function
  priv_execute:
   - userlogin
   - backend
