name: jabber
description: |
 Jabber (XMPP)

 This module sends the following signals:
  - jabber/account

dependencies:
 - dns

priv_all_all:
 - system
priv_usage:
 - userlogin
 - backend

exec_post_install: |
 SELECT system._setup_register_service('jabber', 'jabber');
 SELECT system._setup_register_subservice('jabber', 'account');
 SELECT system._setup_register_subservice('jabber', 'dns_activatable');
