name: site
description: |
 Website

templates:
 - dns.reference_service
 - system.reference_subservice_entity
 - backend.status
 - commons.options

primary_key:
 - domain
 - port

columns:
 -
  name: port
  type: commons.t_port
  description: Port
 -
  name: user
  type: server_access.t_user
  description: Server account under which the htdocs reside
 -
  name: https
  type: commons.t_key
  null: true
  description: If null, HTTPS is deactivated

checks:
 -
  name: valid redirection
  description: Ensure redirect URL exists for redirection
  check: subservice <> 'http_redirect' OR (option->>'redirect_url')::varchar IS NOT NULL

foreign_keys:
 -
  name: https
  columns:
   - domain
   - port
   - https
  ref_table: web.https
  ref_columns:
   - domain
   - port
   - identifier

 -
  name: server_access
  columns:
   - user
   - service_entity_name
  ref_table: server_access.user
  ref_columns:
   - user
   - service_entity_name

unique:
 -
  name: unique
  columns:
   - domain
   - service_entity_name
   - port
