name: site
description: |
 Website

templates:
 - dns.reference_service
 - backend.status

primary_key:
 - domain
 - port

columns:
 -
  name: port
  type: commons.t_port
  description: Port
  default: "80"
 -
  name: user
  type: server_access.t_user
  description: Server account under which the htdocs reside
 -
  name: https
  type: commons.t_key
  null: true
  description: If null, HTTPS is deactivated

foreign_keys:
 -
  name: https
  columns:
   - domain
   - https
  ref_table: web.https
  ref_columns:
   - domain
   - identifier

 -
  name: server_access
  columns:
   - user
   - service_entity_name
  ref_table: server_access.user
  ref_columns:
   - user
   - service_entity_name

unique:
 -
  name: unique
  columns:
   - domain
   - service_entity_name
   - port
